#!/usr/bin/env bash

set +u

export PATH="${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite/steps:${PATH}"

if [[ "${BUILDKITE_LABEL}" == ":github: Deploy Artifacts" ]]; then
  buildkite-agent artifact download "pam_authelia*.tar.gz*" .
  buildkite-agent artifact download "pam_authelia*.deb*" .
  buildkite-agent artifact download "checksums*" .
fi

if [[ "${BUILDKITE_LABEL}" == ":debian: :fedora: :ubuntu: Deploy APT" ]]; then
  buildkite-agent artifact download "pam_authelia_*.deb" .
fi
